server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://db4free.net:3306/tax_calc99
    username: user_99
    password: Tax@2013

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs